import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Sidebar from './Sidebar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Balik Wika',
    description: 'Generated by create next app',
    icons: {
        icon: [
            {
                url: '/favicons/favicon-16x16.png',
                sizes: '16x16',
                type: 'image/png',
            },
            {
                url: '/favicons/favicon-32x32.png',
                sizes: '32x32',
                type: 'image/png',
            },
        ],
        shortcut: '/favicons/favicon.ico',
        apple: '/favicons/apple-touch-icon.png',
        other: [{ rel: 'icon', url: '/favicons/favicon.ico' }],
    },
    manifest: '/favicons/site.webmanifest',
    appleWebApp: {
        capable: true,
        statusBarStyle: 'default',
        title: 'Balik Wika',
    },
    viewport: {
        width: 'device-width',
        initialScale: 1,
        maximumScale: 1,
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className='flex h-screen'>
                    <Sidebar />
                    <main className='flex-1 h-screen overflow-y-auto'>
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
